- name: Uninstall old packages of docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker_packages_to_remove }}"

- name: Docker prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker_prerequisite_packages }}"

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker and Docker Compose
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
      
- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Check Docker service status
  command: systemctl status docker --no-pager
  register: docker_status
  changed_when: false

- name: Print Docker service status
  debug:
    msg: "Docker service status: {{ docker_status.stdout }}"
  when: docker_status.rc == 0